Convert to context
cloudposse/terraform-aws-key-pair pull request #52
Opened 2020-10-13 11:43 UTC by syphernl

## what
* Converted this module to use  `context.tf`

## why
* To follow the new standard applied across the other modules.

2020-10-13 11:43 UTC, syphernl commented
I would really appreciate it if this PR could be tagged with `hacktoberfest-accepted` so it counts towards my [Hacktoberfest](https://hacktoberfest.digitalocean.com/) PR's (since the repo isn't tagged with `hacktoberfest`)

2020-11-17 11:09 UTC, joe-niland requested changes

2020-11-17 11:09 UTC, joe-niland commented on context.tf
> +  source = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2"
Need latest context.tf

2020-11-17 11:09 UTC, joe-niland commented on main.tf
> +  source  = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2"
You could remove the label module

2020-11-17 11:13 UTC, syphernl commented on context.tf
> +  source = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2"
Updated!

2020-11-17 11:14 UTC, syphernl commented on main.tf
> +  source  = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2"
Removed and replaced.

2020-11-17 16:31 UTC, Gowiem commented
/test all

2020-11-17 21:07 UTC, joe-niland commented
/rebuild-readme

2020-11-17 21:53 UTC, joe-niland commented
/test readme

2020-11-17 21:55 UTC, joe-niland commented
/test all

2020-11-17 22:01 UTC, joe-niland approved these changes

2020-11-17 22:01 UTC, merged